### ISSUE TITLE
How to run in lint only (no fixing) mode

### ISSUE THREAD

**Issue by Hurtak** [JamieMason/syncpack-github-action#5]
Hi!

I have the following action

```
name: Test PNPM dependencies are in sync across packages

on:
  push:
    paths:
      - src/pnpm-lock.yaml
      - src/pnpm-workspace.yaml
      - .syncpackrc.json
      - .github/workflows/test-pnpm-synced-dependencies.yml

jobs:
  check-pnpm-lock-versions:
    runs-on: ubuntu-22.04
    name: Test PNPM dependencies are in sync across packages
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: JamieMason/syncpack-github-action@0.2.2
        with:
          package-manager: "pnpm"
          format-mismatches: "ignore"
          lockfile-mismatches: "ignore"
          semver-range-mismatches: "ignore"
          version-mismatches: "lint"
```

Basically it should be lint only, no fixing mode. But when I try to run it it gives the following error

![image](https://user-images.githubusercontent.com/6587821/203111118-e47124c7-0e21-4a37-8516-23e82a4bb314.png)
